# Generated by Django 5.2.7 on 2025-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='index_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
